<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkiverse-parent</artifactId>
    <version>22</version>
  </parent>
  <groupId>io.quarkiverse.camunda</groupId>
  <artifactId>quarkus-camunda-parent</artifactId>
  <name>Quarkus - Camunda - Parent</name>
  <version>999-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>deployment</module>
    <module>runtime</module>
    <module>test</module>
  </modules>
  <scm>
    <connection>scm:git:git@github.com:quarkiverse/quarkus-zeebe.git</connection>
    <developerConnection>scm:git:git@github.com:quarkiverse/quarkus-zeebe.git</developerConnection>
    <url>https://github.com/quarkiverse/quarkus-zeebe</url>
    <tag>HEAD</tag>
  </scm>
  <properties>
    <quarkus.version>3.39.1</quarkus.version>
    <camunda.version>8.9.19</camunda.version>
    <zeebe.testcontainers.version>3.6.9</zeebe.testcontainers.version>
    <quarkus-mockserver.version>1.17.0</quarkus-mockserver.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${quarkus.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.camunda</groupId>
        <artifactId>camunda-client-java</artifactId>
        <version>${camunda.version}</version>
      </dependency>
      <dependency>
        <groupId>io.camunda</groupId>
        <artifactId>camunda-process-test-java</artifactId>
        <version>${camunda.version}</version>
      </dependency>
      <dependency>
        <groupId>io.camunda</groupId>
        <artifactId>zeebe-protocol-jackson</artifactId>
        <version>${camunda.version}</version>
      </dependency>
      <dependency>
        <groupId>io.quarkiverse.mockserver</groupId>
        <artifactId>quarkus-mockserver</artifactId>
        <version>${quarkus-mockserver.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-extension-maven-plugin</artifactId>
          <version>${quarkus.version}</version>
        </plugin>
        <plugin>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-maven-plugin</artifactId>
          <version>${quarkus.version}</version>
          <extensions>true</extensions>
        </plugin>
        <plugin>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-config-doc-maven-plugin</artifactId>
          <version>${quarkus.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${version.compiler.plugin}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  <profiles>
    <profile>
      <id>docs</id>
      <activation>
        <property>
          <name>performRelease</name>
          <value>!true</value>
        </property>
      </activation>
      <modules>
        <module>docs</module>
      </modules>
    </profile>
    <profile>
      <id>it</id>
      <activation>
        <property>
          <name>performRelease</name>
          <value>!true</value>
        </property>
      </activation>
      <modules>
        <module>integration-tests</module>
        <module>examples</module>
      </modules>
    </profile>
  </profiles>
</project>
